groups:
  - name: sql_synth_alerts
    rules:
      # Application Performance Alerts
      - alert: HighQueryLatency
        expr: sql_synth_query_duration_seconds > 5
        for: 2m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High SQL query generation latency"
          description: "Average query generation time is {{ $value }}s, which exceeds the 5s threshold."

      - alert: VeryHighQueryLatency
        expr: sql_synth_query_duration_seconds > 10
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Very high SQL query generation latency"
          description: "Average query generation time is {{ $value }}s, which is critically high."

      - alert: HighErrorRate
        expr: rate(sql_synth_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second over the last 5 minutes."

      - alert: CriticalErrorRate
        expr: rate(sql_synth_errors_total[5m]) > 0.5
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value }} errors per second, which is critically high."

      # System Resource Alerts
      - alert: HighMemoryUsage
        expr: sql_synth_memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%, which exceeds the 85% threshold."

      - alert: CriticalMemoryUsage
        expr: sql_synth_memory_usage_percent > 95
        for: 2m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Critical memory usage"
          description: "Memory usage is {{ $value }}%, which is critically high."

      - alert: HighDiskUsage
        expr: sql_synth_disk_usage_percent > 80
        for: 10m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value }}%, which exceeds the 80% threshold."

      - alert: CriticalDiskUsage
        expr: sql_synth_disk_usage_percent > 90
        for: 5m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Critical disk usage"
          description: "Disk usage is {{ $value }}%, which is critically high."

      # Database Alerts
      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "Database connection failure"
          description: "PostgreSQL database is down or unreachable."

      - alert: SlowDatabaseQueries
        expr: postgres_query_duration_seconds > 2
        for: 3m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries detected"
          description: "Database queries are taking {{ $value }}s on average."

      # Cache Alerts
      - alert: RedisConnectionFailure
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis connection failure"
          description: "Redis cache is down or unreachable."

      - alert: HighRedisMemoryUsage
        expr: redis_memory_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value }}%."

      # Application Health Alerts
      - alert: ApplicationDown
        expr: up{job="sql-synth-app"} == 0
        for: 1m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "SQL Synth application is down"
          description: "The SQL Synth application is not responding to health checks."

      - alert: LowQueryThroughput
        expr: rate(sql_synth_query_total[5m]) < 0.01
        for: 10m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "Low query throughput"
          description: "Query throughput is {{ $value }} queries per second, which is unusually low."

      # Security Alerts
      - alert: HighSecurityErrors
        expr: rate(sql_synth_errors_total{error_type=~"security_.*"}[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "High rate of security errors"
          description: "Security-related errors are occurring at {{ $value }} per second."

      - alert: InjectionAttempts
        expr: increase(sql_synth_errors_total{error_type="sql_injection_attempt"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "SQL injection attempts detected"
          description: "{{ $value }} SQL injection attempts detected in the last 5 minutes."

  - name: infrastructure_alerts
    rules:
      # Container Alerts
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value }}."

      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}."

      # Network Alerts
      - alert: HighNetworkLatency
        expr: prometheus_http_request_duration_seconds{quantile="0.95"} > 1
        for: 5m
        labels:
          severity: warning
          component: network
        annotations:
          summary: "High network latency"
          description: "95th percentile latency is {{ $value }}s."

  - name: business_logic_alerts
    rules:
      # Business Logic Alerts
      - alert: UnusualQueryPatterns
        expr: increase(sql_synth_query_total[1h]) > 1000
        for: 0m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "Unusual query volume"
          description: "{{ $value }} queries processed in the last hour, which is unusually high."

      - alert: HighFailureRate
        expr: rate(sql_synth_errors_total[10m]) / rate(sql_synth_query_total[10m]) > 0.2
        for: 5m
        labels:
          severity: warning
          component: business
        annotations:
          summary: "High query failure rate"
          description: "{{ $value }}% of queries are failing."

      # Performance SLA Alerts
      - alert: SLAViolationLatency
        expr: sql_synth_query_duration_p95_seconds > 3
        for: 5m
        labels:
          severity: warning
          component: sla
        annotations:
          summary: "SLA violation: Query latency"
          description: "95th percentile query latency is {{ $value }}s, violating SLA of 3s."

      - alert: SLAViolationAvailability
        expr: (1 - rate(sql_synth_errors_total[24h]) / rate(sql_synth_query_total[24h])) < 0.999
        for: 0m
        labels:
          severity: critical
          component: sla
        annotations:
          summary: "SLA violation: Availability"
          description: "Service availability is {{ $value }}, below SLA of 99.9%."